name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
    - name: Install system deps
      run: pacman  --noconfirm -Syu ffmpeg rustup gcc clang pkgconf sway git mesa-utils xorg-xwayland
    - name: Install rust
      run: rustup install stable
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Format
      run: cargo fmt --check
    - name: Run tests
      run: |
        XDG_RUNTIME_DIR=/tmp PATH=`pwd`/.github/scripts:$PATH WLR_RENDERER_ALLOW_SOFTWARE=true WLR_BACKENDS=headless WLR_LIBINPUT_NO_DEVICES=1 sway -c .github/scripts/sway.cfg
        exit $(cat /tmp/test_exit_code)

